# Site settings
title: Who is Luiz?
description: On this website you can see information about me, my interests, hobbies, main projects and more.

baseurl: "/aboutme" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Luiz Eduardo
user_description: Software Engineering student at PUCRS, passionate about programming, technology, minimalism, coffee, design, UX, coffee, marketing and coffee!
user_title: Software Engineering Student
email: luiz.reis@edu.pucrs.br
# twitter_username: lorem_ipsum
github_username:  luizeduardomr
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
